server:
  port: 8082
application:
  name: tweets-processing-app
kafka:
  bootstrapAddress: 127.0.0.1:9092
  topic:
    tweets: twitter_tweets_raw
    users: twitter_bot_accounts
    intermediary: twitter_bot_accounts_intermediary

calcbot:
  initialBotProbability: 0.3
  warningWords:
    - register
    - join
    - sign
    - link
    - retweet
    - receive
    - bonus
  modelBotFactorsMap:
    RECENTLY_IN_HOURS: 240
    MIN_FOLLOWERS: 10
    MAX_FOLLOWINGS: 100
    MAX_LIKED_TWEETS: 1000
    MAX_ISSUED_TWEETS: 1000
    MIN_SEC_BETWEEN_TWEETS: 5
    PHOTO_INCREASE_WEIGHT: 5
    PHOTO_DECREASE_WEIGHT: 2
    BACKGROUND_INCREASE_WEIGHT: 4
    CREATING_TIME_INCREASE_WEIGHT:  2
    ACC_NAME_INCREASE_WEIGHT: 3
    DESCRIPTION_INCREASE_WEIGHT: 4
    FOLLOWERS_INCREASE_WEIGHT: 2
    TWEET_CONTENT_INCREASE_WEIGHT: 4
    FAST_TWEETING_INCREASE_WEIGHT: 5