package com.university.twic.calculate.bot.service.twitter;

public enum ModelParameter {
  RECENTLY_IN_HOURS,
  MIN_FOLLOWERS, 
  MAX_FOLLOWINGS, 
  MAX_LIKED_TWEETS, 
  MAX_ISSUED_TWEETS, 
  MIN_SEC_BETWEEN_TWEETS, 
  PHOTO_INCREASE_WEIGHT, 
  PHOTO_DECREASE_WEIGHT, 
  BACKGROUND_INCREASE_WEIGHT, 
  CREATING_TIME_INCREASE_WEIGHT,  
  ACC_NAME_INCREASE_WEIGHT, 
  DESCRIPTION_INCREASE_WEIGHT, 
  FOLLOWERS_INCREASE_WEIGHT, 
  TWEET_CONTENT_INCREASE_WEIGHT, 
  FAST_TWEETING_INCREASE_WEIGHT
}
